import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
import{load,save}from'./store';
import{METHODS,pendingOrder,validateRequest,validateLocation,overdueDays,overdueList,removalCheck}from'./ledger';
const today=()=>new Date().toISOString().slice(0,10);
const blank={title:'',authors:'',year:'2026',venue:'',abstract:'',tags:''};
function App(){const[items,setItems]=useState(load);const[selected,setSelected]=useState(null);const[query,setQuery]=useState('');const[tag,setTag]=useState('全部');const[view,setView]=useState('all');const[show,setShow]=useState(false);const[notice,setNotice]=useState('');const[form,setForm]=useState(blank);const[illForm,setIllForm]=useState({requested:today(),expected:''});const[arriveFor,setArriveFor]=useState(null);const[loc,setLoc]=useState('');const[loanForm,setLoanForm]=useState({borrower:'',lent:today()});const[removing,setRemoving]=useState(null);
useEffect(()=>save(items),[items]);const now=today();
const tags=['全部',...new Set(items.flatMap(x=>x.tags))];
const filtered=useMemo(()=>items.filter(x=>(tag==='全部'||x.tags.includes(tag))&&(`${x.title}${x.authors}${x.abstract}`.toLowerCase().includes(query.toLowerCase()))),[items,tag,query]);
const cur=items.find(x=>x.id===selected)||items[0];
const overdue=useMemo(()=>overdueList(items,now),[items,now]);
const patch=(id,fn)=>setItems(items.map(x=>x.id===id?fn(x):x));
const update=(k,v)=>patch(cur.id,x=>({...x,[k]:v}));
const add=()=>{if(!form.title)return;const p={...form,id:Date.now(),year:+form.year,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),status:'待读',method:'待定',location:'',ill:[],loans:[],cite:`${form.authors} (${form.year}). ${form.title}. ${form.venue}.`};setItems([...items,p]);setSelected(p.id);setForm(blank);setShow(false);setNotice('文献已加入研究库')};
const bib=()=>{navigator.clipboard?.writeText(cur.cite);setNotice('引用文本已复制')};
const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([items.map(x=>x.cite).join('\n')],{type:'text/plain'}));a.download='references.txt';a.click();setNotice('引用列表已导出')};
const addIll=()=>{if(pendingOrder(cur))return setNotice('该文献已有未到货的互借单，不能重复申请');const err=validateRequest(illForm);if(err)return setNotice(err);patch(cur.id,x=>({...x,ill:[...x.ill,{id:Date.now(),...illForm,arrived:null,location:''}]}));setIllForm({requested:today(),expected:''});setNotice('馆际互借申请已登记')};
const arrive=oid=>{const err=validateLocation(loc);if(err)return setNotice(err);patch(cur.id,x=>({...x,location:loc.trim(),ill:x.ill.map(o=>o.id===oid?{...o,arrived:today(),location:loc.trim()}:o)}));setArriveFor(null);setLoc('');setNotice('已登记到货，馆藏位置已更新')};
const addLoan=()=>{if(!loanForm.borrower.trim())return setNotice('请填写借阅人');patch(cur.id,x=>({...x,loans:[...x.loans,{id:Date.now(),borrower:loanForm.borrower.trim(),lent:loanForm.lent||today(),returned:null}]}));setLoanForm({borrower:'',lent:today()});setNotice('借出记录已登记')};
const returnLoan=id=>{patch(cur.id,x=>({...x,loans:x.loans.map(l=>l.id===id?{...l,returned:today()}:l)}));setNotice('已登记归还')};
const rm=items.find(x=>x.id===removing);const rmCheck=rm?removalCheck(rm):null;
const doRemove=()=>{setItems(items.filter(x=>x.id!==removing));setRemoving(null);setNotice('文献已移出研究库')};
return <div className="app"><aside><div className="logo"><span>∴</span> LITERATURE</div><div className="library-head"><span>我的研究库</span><strong>{items.length}<small> 篇文献</small></strong></div><nav><button className={view==='all'?'active':''} onClick={()=>setView('all')}>▤ <span>所有文献</span><b>{items.length}</b></button><button className={view==='overdue'?'active':''} onClick={()=>setView('overdue')}>⚠ <span>逾期互借</span><b className={overdue.length?'red':''}>{overdue.length}</b></button><button>▥ <span>待读</span><b>{items.filter(x=>x.status==='待读').length}</b></button><button>✓ <span>已读</span></button></nav><div className="side-tags"><small>标签</small>{tags.slice(1,5).map(t=><button onClick={()=>setTag(t)} key={t}># {t}</button>)}</div><div className="side-foot"><button>⚙ 偏好设置</button><small>本地数据库 · 已同步</small></div></aside>
<main><header><div><span className="crumb">{view==='overdue'?'RESEARCH / ILL OVERDUE':'RESEARCH / LIBRARY'}</span><h1>{view==='overdue'?'逾期互借':'所有文献'}</h1></div><div className="actions"><button className="outline" onClick={download}>↓ 导出引用</button><button className="primary" onClick={()=>setShow(true)}>＋ 添加文献</button></div></header>
{view==='overdue'?<div className="overdue-page">{overdue.map(({paper,order,days})=><button className="overdue-card" key={order.id} onClick={()=>{setSelected(paper.id);setView('all')}}><div><h3>{paper.title}</h3><p>{paper.authors}</p></div><div className="od-meta"><small>申请日期</small><strong>{order.requested}</strong></div><div className="od-meta"><small>预计到货</small><strong>{order.expected}</strong></div><span className="od-days">逾期 {days} 天</span></button>)}{!overdue.length&&<div className="no-result">当前没有逾期的馆际互借单</div>}</div>
:<><div className="toolbar"><div className="search">⌕<input placeholder="搜索标题、作者或摘要…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}>×</button>}</div><div className="tag-filter">{tags.map(t=><button className={tag===t?'on':''} onClick={()=>setTag(t)} key={t}>{t}</button>)}</div></div>
<div className="body"><section className="paper-list">{filtered.map(p=>{const pend=pendingOrder(p);const d=pend?overdueDays(pend,now):0;return <button className={'paper '+(cur&&cur.id===p.id?'selected':'')} onClick={()=>setSelected(p.id)} key={p.id}><div className="paper-year">{p.year}</div><div className="paper-copy"><h3>{p.title}</h3><p>{p.authors}</p><div>{p.tags.map(t=><span key={t}>#{t}</span>)}</div></div><div className="chips"><small className={'status '+p.status}>{p.status}</small>{d>0&&<small className="status od">逾期{d}天</small>}{pend&&!d&&<small className="status transit">互借在途</small>}</div></button>})}{!filtered.length&&<div className="no-result">没有找到匹配的文献</div>}</section>
<section className="detail">{cur&&<><div className="detail-top"><span className="status reading">{cur.status}</span><button onClick={()=>setNotice('已加入收藏')}>☆ 收藏</button></div><h2>{cur.title}</h2><p className="authors">{cur.authors}</p><div className="cite-actions"><button onClick={bib}>▣ 复制引用</button><button onClick={()=>update('status',cur.status==='已读'?'待读':'已读')}>{cur.status==='已读'?'标记为待读':'标记为已读'}</button></div>
<div className="detail-section"><h4>摘要 <span>ABSTRACT</span></h4><p>{cur.abstract}</p></div>
<div className="detail-section"><h4>出版信息 <span>PUBLICATION</span></h4><div className="pub-grid"><div><small>出版物</small><strong>{cur.venue}</strong></div><div><small>年份</small><strong>{cur.year}</strong></div></div></div>
<div className="detail-section"><h4>全文获取 <span>ACCESS</span></h4><div className="method-row">{METHODS.map(m=><button className={cur.method===m?'on':''} onClick={()=>update('method',m)} key={m}>{m}</button>)}</div>
{cur.method==='馆际互借'?<div className="ill-box">{cur.ill.map(o=>{const d=overdueDays(o,now);return <div className={'ill-order'+(o.arrived?' done':d?' late':'')} key={o.id}><div className="ill-line"><small>申请日期</small><strong>{o.requested}</strong><small>预计到货</small><strong>{o.expected}</strong><span className="ill-state">{o.arrived?'已到货':d?`逾期 ${d} 天`:'在途'}</span></div>{o.arrived?<div className="ill-arrived">到货 {o.arrived} · 馆藏位置 {o.location}</div>:arriveFor===o.id?<div className="ill-arrive"><input placeholder="馆藏位置，如 三楼西架 B-12" value={loc} onChange={e=>setLoc(e.target.value)}/><button className="primary" onClick={()=>arrive(o.id)}>登记到货</button><button onClick={()=>{setArriveFor(null);setLoc('')}}>取消</button></div>:<button className="ill-btn" onClick={()=>{setArriveFor(o.id);setLoc('')}}>到货登记</button>}</div>})}
{pendingOrder(cur)?<p className="ill-hint">该文献已有未到货的互借单，到货登记后才能再次申请。</p>:<div className="ill-form"><label>申请日期<input type="date" value={illForm.requested} onChange={e=>setIllForm({...illForm,requested:e.target.value})}/></label><label>预计到货<input type="date" value={illForm.expected} onChange={e=>setIllForm({...illForm,expected:e.target.value})}/></label><button className="primary" onClick={addIll}>登记互借申请</button></div>}</div>
:<label className="loc-field">馆藏位置<input value={cur.location} onChange={e=>update('location',e.target.value)} placeholder="如 本馆二楼 A-03 / 电子版链接"/></label>}</div>
<div className="detail-section"><h4>借出记录 <span>LOANS</span></h4>{cur.loans.map(l=><div className="loan" key={l.id}><span>{l.borrower}</span><small>借出 {l.lent}</small>{l.returned?<em>已归还 {l.returned}</em>:<button onClick={()=>returnLoan(l.id)}>登记归还</button>}</div>)}{!cur.loans.length&&<p className="ill-hint">暂无借出记录。</p>}<div className="loan-form"><input placeholder="借阅人" value={loanForm.borrower} onChange={e=>setLoanForm({...loanForm,borrower:e.target.value})}/><input type="date" value={loanForm.lent} onChange={e=>setLoanForm({...loanForm,lent:e.target.value})}/><button onClick={addLoan}>登记借出</button></div></div>
<div className="detail-section"><h4>引用文本 <span>BIBTEX / TEXT</span></h4><div className="cite-box">{cur.cite}<button onClick={bib}>复制</button></div></div>
<div className="detail-section"><h4>我的笔记 <span>PRIVATE</span></h4><textarea className="notes" placeholder="记录你的阅读想法…" value={cur.notes||''} onChange={e=>update('notes',e.target.value)}/></div>
<div className="detail-section"><h4>移出文献 <span>REMOVE</span></h4><button className="danger-btn" onClick={()=>setRemoving(cur.id)}>从研究库移出这篇文献</button></div>
</>}</section></div></>}</main>
{show&&<div className="modal-bg"><div className="modal"><button className="close" onClick={()=>setShow(false)}>×</button><span className="crumb">NEW REFERENCE</span><h2>添加一篇文献</h2><label>标题<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="论文或书籍标题"/></label><label>作者<input value={form.authors} onChange={e=>setForm({...form,authors:e.target.value})}/></label><div className="two"><label>年份<input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></label><label>出版物<input value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/></label></div><label>关键词<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="用逗号分隔"/></label><label>摘要<textarea rows="3" value={form.abstract} onChange={e=>setForm({...form,abstract:e.target.value})}/></label><button className="primary full" onClick={add}>保存文献</button></div></div>}
{rm&&rmCheck&&<div className="modal-bg"><div className="modal"><button className="close" onClick={()=>setRemoving(null)}>×</button><span className="crumb">REMOVE REFERENCE</span><h2>移出《{rm.title}》</h2><div className="rm-block"><h5>还在路上的互借单</h5>{rmCheck.orders.length?rmCheck.orders.map(o=><p key={o.id}>申请 {o.requested} · 预计 {o.expected}{overdueDays(o,now)>0&&<b className="red">（已逾期 {overdueDays(o,now)} 天）</b>}</p>):<p className="muted">无</p>}</div><div className="rm-block"><h5>未归还的借出记录</h5>{rmCheck.loans.length?rmCheck.loans.map(l=><p key={l.id}>{l.borrower} · 借出于 {l.lent}</p>):<p className="muted">无</p>}</div>{(rmCheck.orders.length+rmCheck.loans.length)>0&&<p className="rm-warn">以上事务尚未了结，移出后台账将不再追踪。</p>}<button className="danger-btn full" onClick={doRemove}>确认移出</button></div></div>}
{notice&&<div className="toast">{notice}</div>}</div>};
createRoot(document.getElementById('root')).render(<App/>);
